baseURL = "https://yyrise.github.io/docs/"
#languageCode = "en-us"
title = "屁狗多多"
author = "YYRise"
#title = "DOCS"
theme = "zdoc"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = false

copyright = "&copy;{year}, All Rights Reserved"
timeout = 10000
enableEmoji = true
paginate = 13
rssLimit = 100

googleAnalytics = ""

disableKinds = ["taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[taxonomies]
  tag = "tags"

[yuque-sync]
# 用户名
user = "yyrise"
# 知识库路径
kb = "gpesw5"
# 私密仓库需要token
token = "RQ3f2dY7UJJRWKro2TJrkNvKt0Qf0L0WNGU7Qj13"
# api
api = "https://www.yuque.com/api/v2"
# port
port = 8081
# sync after command
aftercmd = ""
# markdown文件目录文件路径为content/${article}
article = "en"
